// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YepPet.Infrastructure.Persistence;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YepPetDbContext))]
    [Migration("20260413120000_AddCountriesAndCities")]
    partial class AddCountriesAndCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.CityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("uq_cities_country_normalized_name");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.CountryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_countries_code");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.FavoriteEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("FavoriteListId")
                        .HasColumnType("uuid")
                        .HasColumnName("favorite_list_id");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteListId")
                        .HasDatabaseName("ix_favorite_entries_favorite_list_id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("FavoriteListId", "PlaceId")
                        .IsUnique()
                        .HasDatabaseName("uq_favorite_entries_list_place");

                    b.ToTable("favorite_entries", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.FavoriteListRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_favorite_lists_owner_user_id");

                    b.ToTable("favorite_lists", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.FeatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_features_code");

                    b.ToTable("features", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.MenuRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("label");

                    b.Property<string>("ParentKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("parent_key");

                    b.Property<string>("Route")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("route");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("uq_menus_key");

                    b.HasIndex("ParentKey");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.MenuRoleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("MenuKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("menu_key");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("MenuKey", "Role")
                        .IsUnique()
                        .HasDatabaseName("uq_menu_roles_menu_key_role");

                    b.ToTable("menu_roles", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PermissionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope_type");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("uq_permissions_key");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PlaceFeatureRecord", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.HasKey("PlaceId", "FeatureId");

                    b.HasIndex("FeatureId")
                        .HasDatabaseName("ix_place_features_feature_id");

                    b.ToTable("place_features", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PlaceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AcceptsCats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("accepts_cats");

                    b.Property<bool>("AcceptsDogs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("accepts_dogs");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("address_line1");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("country");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cover_image_url");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("PetPolicyLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("pet_policy_label");

                    b.Property<string>("PetPolicyNotes")
                        .HasColumnType("text")
                        .HasColumnName("pet_policy_notes");

                    b.Property<string>("PricingLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("pricing_label");

                    b.Property<decimal>("RatingAverage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_average");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("review_count");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_places_city");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_places_type");

                    b.ToTable("places", null, t =>
                        {
                            t.HasCheckConstraint("ck_places_pet_policy", "accepts_dogs OR accepts_cats");

                            t.HasCheckConstraint("ck_places_rating_average", "rating_average >= 0 AND rating_average <= 5");

                            t.HasCheckConstraint("ck_places_review_count", "review_count >= 0");
                        });
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PlaceReviewRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_place_reviews_place_id");

                    b.ToTable("place_reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_place_reviews_score", "score >= 1 AND score <= 5");
                        });
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PlaceTagRecord", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("PlaceId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_place_tags_tag_id");

                    b.ToTable("place_tags", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PrivacyConsentEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_privacy_consent_events_user_id");

                    b.ToTable("privacy_consent_events", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.RolePermissionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("permission_key");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("PermissionKey");

                    b.HasIndex("Role", "PermissionKey")
                        .IsUnique()
                        .HasDatabaseName("uq_role_permissions_role_permission_key");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.TagRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_tags_code");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastAccessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PrivacyAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("privacy_accepted");

                    b.Property<DateTimeOffset?>("PrivacyAcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("privacy_accepted_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.CityRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.CountryRecord", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.FavoriteEntryRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.FavoriteListRecord", "FavoriteList")
                        .WithMany("Entries")
                        .HasForeignKey("FavoriteListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.PlaceRecord", "Place")
                        .WithMany("FavoriteEntries")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavoriteList");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.FavoriteListRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.UserRecord", "OwnerUser")
                        .WithOne("FavoriteList")
                        .HasForeignKey("YepPet.Infrastructure.Persistence.Entities.FavoriteListRecord", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.MenuRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.MenuRecord", null)
                        .WithMany()
                        .HasForeignKey("ParentKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.MenuRoleRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.MenuRecord", "Menu")
                        .WithMany("MenuRoles")
                        .HasForeignKey("MenuKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PlaceFeatureRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.FeatureRecord", "Feature")
                        .WithMany("PlaceFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.PlaceRecord", "Place")
                        .WithMany("PlaceFeatures")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PlaceReviewRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.UserRecord", "AuthorUser")
                        .WithMany("Reviews")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.PlaceRecord", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PlaceTagRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.PlaceRecord", "Place")
                        .WithMany("PlaceTags")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.TagRecord", "Tag")
                        .WithMany("PlaceTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PrivacyConsentEventRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithMany("PrivacyConsentEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.RolePermissionRecord", b =>
                {
                    b.HasOne("YepPet.Infrastructure.Persistence.Entities.PermissionRecord", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.FavoriteListRecord", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.CountryRecord", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.FeatureRecord", b =>
                {
                    b.Navigation("PlaceFeatures");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.MenuRecord", b =>
                {
                    b.Navigation("MenuRoles");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PermissionRecord", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.PlaceRecord", b =>
                {
                    b.Navigation("FavoriteEntries");

                    b.Navigation("PlaceFeatures");

                    b.Navigation("PlaceTags");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.TagRecord", b =>
                {
                    b.Navigation("PlaceTags");
                });

            modelBuilder.Entity("YepPet.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Navigation("FavoriteList");

                    b.Navigation("PrivacyConsentEvents");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
